"""removed course from student

Revision ID: 4c463e6ddd5f
Revises: 94c6c5201954
Create Date: 2023-07-17 17:22:09.567940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c463e6ddd5f'
down_revision = '94c6c5201954'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('course', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
