"""fiexed relationship syntax

Revision ID: 9eb38dc39748
Revises: 4c463e6ddd5f
Create Date: 2023-07-17 20:16:24.247778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb38dc39748'
down_revision = '4c463e6ddd5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
