"""added student name and teacher name to Report_card

Revision ID: aa70e45ab8a4
Revises: 57e0e657e21b
Create Date: 2023-07-17 17:06:26.528639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa70e45ab8a4'
down_revision = '57e0e657e21b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report cards', sa.Column('student_name', sa.String(), nullable=True))
    op.add_column('report cards', sa.Column('teacher_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report cards', 'teacher_name')
    op.drop_column('report cards', 'student_name')
    # ### end Alembic commands ###
